export const triggerContentGeneration = async (payload) => {
    const webhookUrl = import.meta.env.VITE_N8N_WEBHOOK_URL;

    if (!webhookUrl) {
        console.error("n8n Webhook URL not configured");
        // Mock response for development if no URL is set
        return new Promise(resolve => setTimeout(() => resolve({
            script: "Mock Script generated by frontend due to missing webhook.",
            productionPlan: "Mock Production Plan.",
            adsCopy: "Mock Ads Copy."
        }), 1500));
    }

    try {
        const response = await fetch(webhookUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            throw new Error(`n8n webhook failed: ${response.statusText}`);
        }

        return await response.json();
    } catch (error) {
        console.error("Error triggering n8n workflow:", error);
        throw error;
    }
};
