-- Create Campaigns Table
create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  status text default 'draft',
  -- 'active', 'draft', 'completed'
  progress integer default 0,
  description text
);
-- Create Content Items Table
create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  campaign_id bigint references public.campaigns,
  title text not null,
  type text not null,
  -- 'reel', 'post', 'story'
  status text default 'idea',
  -- 'idea', 'scripted', 'ready', 'published'
  scheduled_date timestamp with time zone,
  -- AI Generated Content
  script_content text,
  production_plan text,
  ads_copy text,
  -- Metadata
  idea_prompt text,
  image_url text
);
-- Enable Row Level Security (RLS)
alter table public.campaigns enable row level security;
alter table public.content_items enable row level security;
-- Create Policies (Open for now as it's a personal tool, but can be restricted later)
drop policy if exists "Enable all access for all users" on public.campaigns;
create policy "Enable all access for all users" on public.campaigns for all using (true) with check (true);
drop policy if exists "Enable all access for all users" on public.content_items;
create policy "Enable all access for all users" on public.content_items for all using (true) with check (true);
-- Insert Mock Data safely
do $$ begin if not exists (
  select 1
  from public.campaigns
  limit 1
) then
insert into public.campaigns (title, status, progress)
values ('Lanzamiento Reto Verano', 'active', 65),
  ('Webinar Nutrición', 'draft', 20),
  ('Branding Personal Abril', 'active', 40);
insert into public.content_items (campaign_id, title, type, status, scheduled_date)
select id,
  'Reel: 3 Errores Sentadilla',
  'reel',
  'scripted',
  now() + interval '2 days'
from public.campaigns
where title = 'Lanzamiento Reto Verano';
insert into public.content_items (campaign_id, title, type, status, scheduled_date)
select id,
  'Post: Beneficios Creatina',
  'post',
  'idea',
  now() + interval '4 days'
from public.campaigns
where title = 'Lanzamiento Reto Verano';
end if;
end $$;
-- Create Chat Messages Table for Persistence
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  role text not null,
  -- 'user', 'assistant', 'system'
  content text not null
);
-- RLS for Chat Messages
alter table public.chat_messages enable row level security;
drop policy if exists "Enable all access for all users" on public.chat_messages;
create policy "Enable all access for all users" on public.chat_messages for all using (true) with check (true);
-- Create Brand Voices Table
create table if not exists public.brand_voices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  tone_instructions text not null,
  is_default boolean default false
);
-- RLS for Brand Voices
alter table public.brand_voices enable row level security;
drop policy if exists "Enable all access for all users" on public.brand_voices;
create policy "Enable all access for all users" on public.brand_voices for all using (true) with check (true);
-- Insert Default Brand Voices
insert into public.brand_voices (name, description, tone_instructions, is_default)
values (
    'Entrenador Estándar',
    'Tono equilibrado, profesional y motivador',
    'Usa un tono profesional pero cercano. Motiva sin ser exagerado. Enfócate en la técnica y la constancia.',
    true
  ),
  (
    'Vendedor Agresivo',
    'Enfocado en cierre de ventas y dolor',
    'Usa un tono directo, enfocado en los puntos de dolor del cliente. Urgencia y escasez. Llamadas a la acción muy claras y fuertes.',
    false
  ),
  (
    'Amigo Cercano',
    'Informal, uso de emojis, jerga suave',
    'Habla como si fueras un amigo de toda la vida. Usa emojis, lenguaje relajado, "tú a tú". Empático y comprensivo.',
    false
  );
-- Create Students Table
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  email text,
  age integer,
  height numeric,
  -- in cm
  weight numeric,
  -- in kg
  body_fat_pct numeric,
  activity_level numeric default 1.2,
  -- Sedentario (1.2) a Muy Activo (1.9)
  goal text default 'maintenance',
  -- 'cut', 'bulk', 'recomp', 'maintenance'
  last_payment_date date,
  last_routine_date date,
  next_payment_date date,
  next_checkin_date date,
  next_videocall_date timestamptz,
  remaining_checks integer default 0
);
-- Create Measurements Table (Progress Tracking)
create table if not exists public.student_measurements (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  weight numeric not null,
  body_fat_pct numeric,
  photo_url text -- Reference to Storage
);
-- RLS for Students and Measurements
alter table public.students enable row level security;
alter table public.student_measurements enable row level security;
drop policy if exists "Enable all access for all users" on public.students;
create policy "Enable all access for all users" on public.students for all using (true) with check (true);
drop policy if exists "Enable all access for all users" on public.student_measurements;
create policy "Enable all access for all users" on public.student_measurements for all using (true) with check (true);
-- Function to calculate BMR and Macros (Híbrida: SQL Power)
create or replace function calculate_macros(
    p_weight numeric,
    p_height numeric,
    p_age integer,
    p_activity_level numeric,
    p_goal text,
    p_protein_grams numeric,
    p_fat_grams numeric
  ) returns json as $$
declare tmb numeric;
tdee numeric;
target_calories numeric;
protein_cals numeric;
fat_cals numeric;
carb_cals numeric;
carb_grams numeric;
begin -- Mifflin-St Jeor Equation (Male version as default, can be extended)
tmb := (10 * p_weight) + (6.25 * p_height) - (5 * p_age) + 5;
tdee := tmb * p_activity_level;
-- Apply Goal Multiplier
if p_goal = 'cut' then target_calories := tdee * 0.8;
-- 20% Deficit
elsif p_goal = 'bulk' then target_calories := tdee * 1.1;
-- 10% Surplus
else target_calories := tdee;
end if;
-- Macros Calculation
protein_cals := p_protein_grams * 4;
fat_cals := p_fat_grams * 9;
carb_cals := target_calories - protein_cals - fat_cals;
if carb_cals < 0 then carb_cals := 0;
end if;
carb_grams := carb_cals / 4;
return json_build_object(
  'bmr',
  round(tmb, 0),
  'tdee',
  round(tdee, 0),
  'target_calories',
  round(target_calories, 0),
  'protein_g',
  p_protein_grams,
  'fat_g',
  p_fat_grams,
  'carbs_g',
  round(carb_grams, 0)
);
end;
$$ language plpgsql;
-- Create Student Plans Table
create table if not exists public.student_plans (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  calories integer not null,
  protein_g integer not null,
  fat_g integer not null,
  carbs_g integer not null,
  goal text,
  nutrition_plan_text text,
  training_plan_text text
);
-- RLS for Student Plans
alter table public.student_plans enable row level security;
drop policy if exists "Enable all access for all users" on public.student_plans;
create policy "Enable all access for all users" on public.student_plans for all using (true) with check (true);
-- Insert Mock Students
insert into public.students (
    full_name,
    age,
    height,
    weight,
    activity_level,
    goal
  )
values ('Juan Pérez', 28, 175, 82, 1.55, 'cut'),
  (
    'María García',
    32,
    162,
    65,
    1.375,
    'maintenance'
  ),
  ('Carlos Ruiz', 24, 180, 75, 1.725, 'bulk') on conflict do nothing;
-- Create Student Sessions Table (History of completed calls/meetings)
create table if not exists public.student_sessions (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  session_date timestamp with time zone not null,
  session_type text not null,
  -- 'initial', 'follow_up', 'other'
  notes text,
  metrics_updated boolean default false
);
-- RLS for Student Sessions
alter table public.student_sessions enable row level security;
drop policy if exists "Enable all access for all users" on public.student_sessions;
create policy "Enable all access for all users" on public.student_sessions for all using (true) with check (true);