-- Create Campaigns Table
create table public.campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  status text default 'draft', -- 'active', 'draft', 'completed'
  progress integer default 0,
  description text
);

-- Create Content Items Table
create table public.content_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  campaign_id bigint references public.campaigns,
  title text not null,
  type text not null, -- 'reel', 'post', 'story'
  status text default 'idea', -- 'idea', 'scripted', 'ready', 'published'
  scheduled_date timestamp with time zone,
  
  -- AI Generated Content
  script_content text,
  production_plan text,
  ads_copy text,
  
  -- Metadata
  idea_prompt text
);

-- Enable Row Level Security (RLS)
alter table public.campaigns enable row level security;
alter table public.content_items enable row level security;

-- Create Policies (Open for now as it's a personal tool, but can be restricted later)
create policy "Enable all access for all users" on public.campaigns
for all using (true) with check (true);

create policy "Enable all access for all users" on public.content_items
for all using (true) with check (true);

-- Insert Mock Data for testing
insert into public.campaigns (title, status, progress) values
('Lanzamiento Reto Verano', 'active', 65),
('Webinar Nutrición', 'draft', 20),
('Branding Personal Abril', 'active', 40);

insert into public.content_items (campaign_id, title, type, status, scheduled_date) values
(1, 'Reel: 3 Errores Sentadilla', 'reel', 'scripted', now() + interval '2 days'),
(1, 'Post: Beneficios Creatina', 'post', 'idea', now() + interval '4 days');

-- Create Chat Messages Table for Persistence
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  role text not null, -- 'user', 'assistant', 'system'
  content text not null
);

-- RLS for Chat Messages
alter table public.chat_messages enable row level security;

create policy "Enable all access for all users" on public.chat_messages
for all using (true) with check (true);

-- Create Brand Voices Table
create table public.brand_voices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  tone_instructions text not null,
  is_default boolean default false
);

-- RLS for Brand Voices
alter table public.brand_voices enable row level security;

create policy "Enable all access for all users" on public.brand_voices
for all using (true) with check (true);

-- Insert Default Brand Voices
insert into public.brand_voices (name, description, tone_instructions, is_default) values
('Entrenador Estándar', 'Tono equilibrado, profesional y motivador', 'Usa un tono profesional pero cercano. Motiva sin ser exagerado. Enfócate en la técnica y la constancia.', true),
('Vendedor Agresivo', 'Enfocado en cierre de ventas y dolor', 'Usa un tono directo, enfocado en los puntos de dolor del cliente. Urgencia y escasez. Llamadas a la acción muy claras y fuertes.', false),
('Amigo Cercano', 'Informal, uso de emojis, jerga suave', 'Habla como si fueras un amigo de toda la vida. Usa emojis, lenguaje relajado, "tú a tú". Empático y comprensivo.', false);
