-- Create Student Tasks Table
create table if not exists public.student_tasks (
    id bigint generated by default as identity primary key,
    student_id bigint references public.students on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    task_type text not null,
    -- 'payment', 'checkin', 'video_call', 'other'
    title text,
    due_date timestamp with time zone not null,
    status text default 'pending',
    -- 'pending', 'completed', 'cancelled'
    completed_at timestamp with time zone,
    notes text
);
-- RLS for Student Tasks
alter table public.student_tasks enable row level security;
drop policy if exists "Enable all access for all users" on public.student_tasks;
create policy "Enable all access for all users" on public.student_tasks for all using (true) with check (true);