-- Create Foods Table
create table if not exists public.foods (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    calories_per_100g integer not null,
    protein_per_100g numeric not null,
    carbs_per_100g numeric not null,
    fat_per_100g numeric not null,
    category text -- 'protein', 'carb', 'fat', 'fruit', 'vegetable', 'other'
);
-- Enable RLS
alter table public.foods enable row level security;
create policy "Enable read access for all users" on public.foods for
select using (true);
create policy "Enable write access for all users" on public.foods for all using (true) with check (true);
-- Seed Data (Basic Bodybuilding Foods)
insert into public.foods (
        name,
        calories_per_100g,
        protein_per_100g,
        carbs_per_100g,
        fat_per_100g,
        category
    )
values (
        'Pechuga de Pollo (Cocida)',
        165,
        31,
        0,
        3.6,
        'protein'
    ),
    (
        'Carne Molida 5% (Cocida)',
        137,
        21.4,
        0,
        5,
        'protein'
    ),
    (
        'Atún en Agua (Drenado)',
        116,
        26,
        0,
        0.8,
        'protein'
    ),
    (
        'Huevo Entero (Grande)',
        143,
        12.6,
        0.7,
        9.5,
        'protein'
    ),
    ('Claras de Huevo', 52, 11, 0.7, 0.2, 'protein'),
    ('Salmón (Cocido)', 208, 20, 0, 13, 'protein'),
    ('Whey Protein (Polvo)', 370, 75, 4, 3, 'protein'),
    (
        'Arroz Blanco (Cocido)',
        130,
        2.7,
        28,
        0.3,
        'carb'
    ),
    (
        'Arroz Integral (Cocido)',
        111,
        2.6,
        23,
        0.9,
        'carb'
    ),
    (
        'Papa / Patata (Cocida)',
        87,
        1.9,
        20,
        0.1,
        'carb'
    ),
    (
        'Camote / Batata (Cocida)',
        86,
        1.6,
        20,
        0.1,
        'carb'
    ),
    ('Avena (Cruda)', 389, 16.9, 66, 6.9, 'carb'),
    ('Pasta (Cocida)', 131, 5, 25, 1.1, 'carb'),
    (
        'Pan Integral (Rebanada)',
        252,
        12,
        43,
        3.5,
        'carb'
    ),
    ('Tortilla de Maíz', 218, 5.7, 45, 2.9, 'carb'),
    ('Palta / Aguacate', 160, 2, 8.5, 14.7, 'fat'),
    ('Aceite de Oliva', 884, 0, 0, 100, 'fat'),
    ('Mantequilla de Maní', 588, 25, 20, 50, 'fat'),
    ('Almendras', 579, 21, 22, 49, 'fat'),
    ('Nueces', 654, 15, 14, 65, 'fat'),
    ('Manzana', 52, 0.3, 14, 0.2, 'fruit'),
    ('Banana / Plátano', 89, 1.1, 23, 0.3, 'fruit'),
    ('Frutillas / Fresas', 32, 0.7, 7.7, 0.3, 'fruit'),
    ('Arándanos', 57, 0.7, 14, 0.3, 'fruit'),
    ('Brócoli (Cocido)', 35, 2.4, 7, 0.4, 'vegetable'),
    (
        'Espinaca (Cruda)',
        23,
        2.9,
        3.6,
        0.4,
        'vegetable'
    ),
    (
        'Zanahoria (Cruda)',
        41,
        0.9,
        10,
        0.2,
        'vegetable'
    );